name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Build Electron app (Windows)
        run: npm run build:windows

      - name: Create Windows ZIP
        run: |
          cd release
          $zipFile = Get-ChildItem -Filter "*.zip" | Select-Object -First 1
          if ($zipFile) {
            Copy-Item $zipFile.FullName -Destination ../TradeHarbour-Windows.zip
          } else {
            Write-Host "No ZIP file found, checking for other formats..."
            Get-ChildItem
          }
          cd ..
        shell: pwsh

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: TradeHarbour-Windows
          path: TradeHarbour-Windows.zip

  release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true

      - name: Display structure
        run: ls -R

      - name: Create Release Notes
        run: |
          echo "# TradeHarbour Desktop - Windows Build" > release-notes.md
          echo "" >> release-notes.md
          echo "## Downloads" >> release-notes.md
          echo "" >> release-notes.md
          echo "- **TradeHarbour-Windows.zip** - For Windows (x64)" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Windows Installation" >> release-notes.md
          echo "1. Download TradeHarbour-Windows.zip" >> release-notes.md
          echo "2. Extract the ZIP file" >> release-notes.md
          echo "3. Run Trade Harbour.exe" >> release-notes.md
          echo "" >> release-notes.md
          echo "Built on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> release-notes.md

      - name: Create/Update Latest Release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: latest
          name: Latest Build
          body_path: release-notes.md
          files: |
            TradeHarbour-Windows/TradeHarbour-Windows.zip
          prerelease: false
          draft: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Status
        if: success()
        run: echo "✅ Release created successfully!"

      - name: Release Failed - Artifacts Available
        if: failure()
        run: |
          echo "⚠️ Release creation failed, but build artifacts are available for manual download"
          echo "Download from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
