name: Windows Release Portable

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: |
        npm run build:main
        npm run build:renderer

    - name: Build Windows executables
      run: npx electron-builder --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload executables as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TradeHarbour-Windows-Portable-${{ github.ref_name }}
        path: release/*.exe
        retention-days: 90

    - name: Create Release (Simple)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.exe
        name: Trade Harbour ${{ github.ref_name }} - Windows Portable
        body: |
          # Trade Harbour ${{ github.ref_name }} - Windows Portable Release

          ## 💾 Portable Application
          This is a **100% portable application** - no installation required!

          ## Downloads
          - **Trade Harbour Setup.exe** - Traditional installer (creates shortcuts)
          - **TradeHarbour-portable.exe** - Portable version (recommended)

          ## ✨ Features
          - **True Portability**: Data stored in `data/` folder next to .exe
          - **USB Friendly**: Run from anywhere - USB drives, cloud folders
          - **Easy Backups**: Just copy the entire folder
          - **No Registry**: Leaves your system completely clean

          ## 🚀 Usage
          1. Download **TradeHarbour-portable.exe** (recommended)
          2. Create a folder (e.g., "Trade Harbour")
          3. Place the .exe in the folder
          4. Run it - a `data/` folder will be created automatically
          5. Add your API keys and start trading!

          ## 📋 Requirements
          - Windows 10/11 (64-bit)
          - No additional software needed

          ## 🔄 Upgrading
          - **Easy**: Copy your `data/` folder to the new version
          - **Easier**: Just replace the .exe file in your current folder
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}