name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Build Windows executables
      run: |
        npm run build:main
        npm run build:renderer
        npx electron-builder --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List generated files
      shell: pwsh
      run: |
        Write-Host "Contents of release directory:"
        if (Test-Path "release") { Get-ChildItem release } else { Write-Host "Release directory does not exist" }
        Write-Host "Looking for exe files:"
        Get-ChildItem release -Filter "*.exe" -Recurse -ErrorAction SilentlyContinue

    - name: Create Release and Upload Assets
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: |
        $tagName = "${{ github.ref_name }}"

        # Create release using GitHub CLI (or use existing if it exists)
        gh release create $tagName --title "Trade Harbour $tagName" --notes "Trade Harbour release $tagName - Download and run the .exe file directly!" || echo "Release already exists"

        # Upload only the main distribution files (not helper files)
        Get-ChildItem release -Filter "*Setup*.exe" -Recurse | ForEach-Object {
          Write-Host "Uploading installer: $($_.FullName)"
          gh release upload $tagName $_.FullName --clobber
        }

        Get-ChildItem release -Filter "*portable*.exe" -Recurse | ForEach-Object {
          Write-Host "Uploading portable: $($_.FullName)"
          gh release upload $tagName $_.FullName --clobber
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}