name: Windows Release Portable

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: |
        npm run build:main
        npm run build:renderer

    - name: Build Windows executables
      run: npx electron-builder --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ZIP packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TradeHarbour-Windows-Portable-${{ github.ref_name }}
        path: release/*.zip
        retention-days: 90

    - name: Create Release (Simple)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.zip
        name: Trade Harbour ${{ github.ref_name }} - Windows Portable
        body: |
          # Trade Harbour ${{ github.ref_name }} - Windows Portable Release

          ## 📦 Complete Package Download
          This is a **100% portable application** delivered as a ZIP package!

          ## Downloads
          - **TradeHarbour-portable.zip** - Complete portable package (includes .exe, data folder, and troubleshooting tools)

          ## ✨ What's Included in the ZIP
          - **TradeHarbour.exe** - Main application
          - **data/** folder - Your settings and trade data storage
          - **install-dependencies.bat** - Automated dependency installer
          - **fix-white-screen.bat** - Quick troubleshooting tool
          - **Complete documentation** - Upgrade instructions and user guides

          ## 🚀 Usage
          1. Download **TradeHarbour-portable.zip**
          2. Extract to any folder (desktop, USB drive, etc.)
          3. Run **TradeHarbour.exe** from the extracted folder
          4. Add your API keys and start trading!

          ## 📋 Requirements
          - Windows 10/11 (64-bit)
          - If you get a white screen, run **fix-white-screen.bat**

          ## 🔄 Upgrading
          - **Simple**: Copy the `data/` folder from old version to new extracted folder
          - **Visible**: Data folder is included in ZIP so you can see exactly what to copy
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}