name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Build Windows executables
      run: |
        npm run build:main
        npm run build:renderer
        npx electron-builder --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List generated files
      shell: pwsh
      run: |
        Write-Host "Contents of release directory:"
        if (Test-Path "release") { Get-ChildItem release } else { Write-Host "Release directory does not exist" }
        Write-Host "Looking for exe files:"
        Get-ChildItem release -Filter "*.exe" -Recurse -ErrorAction SilentlyContinue

    - name: Create Release and Upload Assets
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Creating release ${{ github.ref_name }}"
        gh release create ${{ github.ref_name }} --title "Trade Harbour ${{ github.ref_name }}" --notes "Trade Harbour release ${{ github.ref_name }} - Download and run the .exe file directly!" || echo "Release might already exist"

        echo "Looking for exe files to upload..."
        find release -name "*.exe" -type f

        echo "Uploading all exe files..."
        find release -name "*Setup*.exe" -type f -exec gh release upload ${{ github.ref_name }} {} --clobber \;
        find release -name "*portable*.exe" -type f -exec gh release upload ${{ github.ref_name }} {} --clobber \;
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}